name: mysite
favicon: null
layout_spectrum: 0.3746233247220516
typography_spectrum: 0.6781807339284569
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.43058411427773535
  lightness: 0.04056638898327947
  saturation: 0.23385978979058564
  rhythmicContrast: 0.2656833198852837
purpose: []
